### ISSUE TITLE
Update SlaterGPU

### ISSUE THREAD

**Issue by ndmeier25** [ZimmermanGroup/SlaterGPU#2]
Goal is to update SlaterGPU with 2024 files

- [x] test compilation of current state to make sure we start from a state that compiles / runs
- [x] start pulling files from Paul's directory on athena into this repo, check the diffs, and commmit whatever looks reasonable
     - [x] gamma.cpp 
     - [x] get_rcutoff.cpp (no equivalent in Paul's version)
     - [x] grid_util.cpp (no equivalent in Paul's version)
     - [x] integrals.cpp
     - [x] integrals_d.cpp 
     - [x] integrals_aux.cpp
     - [x] lebedev2.cpp
     - [x] murak.cpp
     - [x] pVp.cpp
     - [x] reduce.cpp
     - [x] spherical.cpp
     - [x] Vinr.cpp
     - [x] gamma.h
     - [x] integrals.h
     - [x] lebedev2.h
     - [x] murak,h
     - [x] pVp.h
     - [x] write.h
     - [x] Vinr.h
     - [x] reduce.h
     - [x] spherical.h
     - [x] becke.h
     - [x] sortUtil.h
     - [x] braggslater.h
 
- [x] for anything that looks ambiguous, make a list here and then we can bring those things to Paul

-      becke.cpp / h 
  (Old Becke functions were in integrals.cpp, so just brought over the functions actually called)

- [x] move header files to consistent location
-      SlaterGPU/include/
- [x] Bring over double precision version of certain files
     - [x] sphericald.cpp 
     - [x] pvpd.cpp

- [x] Add prolate spheroidal files/headers
     - [x]  integrals_ps.cpp
     - [x]  ps_grid.cpp
     - [x] prosph.cpp
     - [x] prosph.h
     - [x] quad.cpp
     - [x] quad.h
     - [x] ps_first_second_order.cpp (?)

- [x] Remove FP1/FP2 dependency
- [x] Remove libcint/libcintw dependency (can put back if GTO functionality is reinstated)
- [x] Add source file to set up environment efficiently

**Comment by ndmeier25** [comment]
Managed to compile current state after including a source file and omitting the examples directory from the CMake file, as libcint is required for GTO's in the test_gto_grid folder, which is not necessary at the moment. However, I'm unsure how to test it, as an executable was not generated.

**Comment by ndmeier25** [comment]
Header files moved to include directory, CMakeLists.txt had to be updated to add include directory to CMake path and remove them from src directory.

**Comment by joshkamm** [comment]
When talking with Paul he thought we should get the first round of code changes merged into the main branch and then do the prolate spheroidal coordinates stuff as a second round, which I think would correspond to merging #3 before #7
